images:
  server: quay.io/infinispan/server:latest
  initContainer: registry.access.redhat.com/ubi8-micro
deploy:
  security:
    authentication: true
    secretName: karavan-infinispan
  replicas: 1
  container:
    storage:
      ephemeral: true
  expose:
    type: NodePort
    nodePort: 32666