apiVersion: v1
kind: Secret
metadata:
  name: karavan-infinispan
type: Opaque
stringData:
  username: monitor
  password: password
  identities-batch: |-
    user create admin -p admin -g admin
    user create monitor -p password --users-file metrics-users.properties --groups-file metrics-groups.properties
