name: cli 

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  TAG: 3.20.2-SNAPSHOT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Karavan
        uses: actions/checkout@v3
        with:
          path: karavan

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/camel/karavan
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      
      #  Build Karavan cli
      - name: Build Karavan cli
        working-directory: ./karavan
        run: |
          mvn package -f karavan-cli 
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Karavan cli (upload)
        uses: actions/upload-artifact@v3
        with:
          name: karavan-cli.jar
          path: ./karavan/karavan-cli/target/karavan-cli-${{ env.TAG }}.jar
        if: ${{ github.ref == 'refs/heads/main' }}