apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: "karavan"
  app.kubernetes.io/part-of: "karavan"
  app.kubernetes.io/name: "karavan"
  app.kubernetes.io/version: "4.4.0"
namespace: "karavan"
resources:
  - secret.yaml
  - role.yaml
  - service-account.yaml
  - role-binding.yaml
  - deployment.yaml
  - service.yaml

# Replace secret from.env if required
secretGenerator:
- name: karavan
  behavior: replace
  options:
      disableNameSuffixHash: true
  envs:
    - .env